"""
SentryWP — PDF Report Generator
=================================
Wraps the existing generate_pdf.py logic to produce a branded
security report PDF for each client site scan.
"""

import os
import json
import datetime
from pathlib import Path


def generate_pdf_report(result: dict, client: dict, reports_dir: Path) -> Path | None:
    """
    Generate a PDF security report for a site scan result.
    Returns the path to the generated PDF, or None on failure.
    """
    try:
        # Build markdown report content
        md_content = _build_markdown_report(result, client)

        # Write temp markdown file
        site_id   = result["site_id"]
        timestamp = result["timestamp"]
        md_path   = reports_dir / f"{site_id}_{timestamp}_report.md"
        pdf_path  = reports_dir / f"{site_id}_{timestamp}_report.pdf"

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        # Use the existing generate_pdf.py logic
        _convert_md_to_pdf(md_path, pdf_path)

        if pdf_path.exists():
            print(f"  📄 PDF report generated: {pdf_path.name}")
            return pdf_path
        else:
            print(f"  [-] PDF generation failed (file not found after conversion)")
            return None

    except Exception as e:
        print(f"  [-] PDF report error: {e}")
        return None


def _build_markdown_report(result: dict, client: dict) -> str:
    ai         = result.get("ai") or {}
    severity   = ai.get("severity", "unknown").upper()
    scan_data  = result.get("scan_data") or {}
    timestamp  = result.get("timestamp", "")
    actions    = result.get("actions", [])

    core_mods  = scan_data.get("core_modifications", [])
    anomalies  = scan_data.get("suspicious_anomalies", [])
    uploads    = scan_data.get("suspicious_uploads", [])

    severity_color = {
        "CLEAN":    "🟢",
        "LOW":      "🟡",
        "MEDIUM":   "🟠",
        "HIGH":     "🔴",
        "CRITICAL": "🚨",
    }.get(severity, "❓")

    lines = [
        f"# SentryWP Security Report",
        f"",
        f"**Client:** {client['name']}",
        f"**Website:** {result['url']}",
        f"**Scan Date:** {timestamp} UTC",
        f"**Report Generated By:** Muhammad Riasat Ali — Web Developer & WordPress Security Specialist",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"| Field | Value |",
        f"|---|---|",
        f"| Overall Status | {severity_color} **{severity}** |",
        f"| AI Confidence | {ai.get('confidence', 0):.0%} |",
        f"| Threat Type | {ai.get('threat_type', 'N/A')} |",
        f"| Files Scanned | {scan_data.get('total_files_scanned', 0)} |",
        f"| Core Modifications | {len(core_mods)} |",
        f"| Suspicious Anomalies | {len(anomalies)} |",
        f"| Suspicious Uploads | {len(uploads)} |",
        f"",
        f"**AI Summary:** {ai.get('summary', 'No summary available.')}",
        f"",
        f"---",
        f"",
    ]

    # Core modifications
    if core_mods:
        lines += [
            f"## 🔴 WordPress Core Modifications",
            f"",
            f"These WordPress core files have been tampered with. This is a strong indicator of malware injection.",
            f"",
        ]
        for item in core_mods[:20]:
            lines.append(f"- `{item.get('file', '')}` — MD5 mismatch")
        lines.append("")

    # Suspicious anomalies
    if anomalies:
        lines += [
            f"## 🟠 Suspicious Code Anomalies",
            f"",
        ]
        for item in anomalies[:20]:
            lines += [
                f"**File:** `{item.get('file', '')}`  (Line {item.get('line', '?')})",
                f"**Reason:** {item.get('reason', '')}",
                f"**Snippet:** `{item.get('snippet', '')[:100]}`",
                f"",
            ]

    # Bad uploads
    if uploads:
        lines += [
            f"## 🚨 PHP Files in Uploads Directory",
            f"",
            f"PHP files in the uploads directory are always malicious. WordPress never places PHP files there.",
            f"",
        ]
        for item in uploads[:20]:
            lines += [
                f"- `{item.get('file', '')}` ({item.get('size', 0)} bytes)",
            ]
        lines.append("")

    # Actions taken
    if actions and actions != ["alert_only"]:
        lines += [
            f"## ✅ Automated Remediation Actions",
            f"",
            f"The following security layers were automatically deployed:",
            f"",
        ]
        for action in actions:
            lines.append(f"- {action}")
        lines.append("")
    elif severity in ("HIGH", "MEDIUM"):
        lines += [
            f"## ⚠️ Recommended Actions",
            f"",
            ai.get("remediation", "Manual review required."),
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"## About SentryWP",
        f"",
        f"This report was automatically generated by **SentryWP Automation** — ",
        f"a 24/7 WordPress security monitoring system built and operated by",
        f"**Muhammad Riasat Ali**, Web Developer & WordPress Security Specialist.",
        f"",
        f"*For questions about this report, please contact your web developer.*",
    ]

    return "\n".join(lines)


def _convert_md_to_pdf(md_path: Path, pdf_path: Path):
    """
    Convert markdown to PDF using markdown + weasyprint or
    falling back to a simple HTML + Edge/Chrome print-to-PDF approach.
    """
    try:
        import markdown
        from weasyprint import HTML

        with open(md_path, "r", encoding="utf-8") as f:
            md_text = f.read()

        html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; color: #333; line-height: 1.6; }}
  h1   {{ color: #1a1a2e; border-bottom: 3px solid #e74c3c; padding-bottom: 10px; }}
  h2   {{ color: #2c3e50; border-left: 4px solid #3498db; padding-left: 12px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th,td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th    {{ background: #2c3e50; color: white; }}
  code  {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: monospace; }}
  hr    {{ border: none; border-top: 1px solid #eee; margin: 24px 0; }}
</style>
</head>
<body>
{markdown.markdown(md_text, extensions=['tables', 'fenced_code'])}
</body>
</html>"""

        HTML(string=html_content).write_pdf(str(pdf_path))

    except ImportError:
        # weasyprint not available — save HTML as fallback
        html_path = pdf_path.with_suffix(".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        print(f"  ⚠️  weasyprint not available — saved as HTML: {html_path.name}")
